excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://datasciencemonkey.github.io
title: Another blog on all things Analytics
email: datasciencemonkey@gmail.com
tagline: 
description: Analytics, Data Science and More...
paginate: 5
google_analytics: UA-79207830-1
