excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://datasciencemonkey.github.io
title: Another Blog on All Things Analytics
tagline: 
description: Analytics, Data Science and More...
paginate: 5
