excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://datasciencemonkey.github.io
title: Get Set Go!
tagline: 
description: On Analytics, Data Science and More...
paginate: 5
google_analytics: UA-79207830-1
